### ISSUE TITLE
Avoiding the program to crash when the `/usr/share/pcsc/smartcard_list.txt` file cannot be found when calling the `find_info()` function.

### ISSUE THREAD

**Issue by T-TROUCHKINE** [Ledger-Donjon/scaffold#5]
Hello,

I think it is interesting to avoid the crash of the program when the `/usr/share/pcsc/smartcard_list.txt` file cannot be found while calling the `find_info()` function as it is system dependent and avoid the example `secaes-atmega.py` to work out of the box.

It may also be interesting to customize the location of this file or even be able to directly fetch it online.

Regards !

**Comment by kingofpayne** [comment]
Missing the ATR list file should not be silent, we want users to be aware it must be installed.
Maybe a good solution would be to raise a `MissingATRDatabase` exception and print warning message in the example files to prevent crashes.

For the customization part, I propose to add an optional argument to the `find_info` method so the user can pass a path to the file directly.

About fetching the file online, we can try that as a fallback when the list is not installed and when the user did not supply a path to the file.
